version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./laravel/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./laravel/
      - save_cache:
          key: composer-v1-{{ checksum "./laravel/composer.lock" }}
          paths:
            - ./laravel/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./laravel/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d ./laravel/node_modules ]; then
              cd laravel/; npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "./laravel/package-lock.json" }}
          paths:
            - ./laravel/node_modules
      - run: cd laravel/; npm run dev
